### ISSUE TITLE
error: cannot find symbol variable MyObjectBox

### ISSUE THREAD

**Issue by triasbrata** [greenrobot/ObjectBox#132]
hy im new in android programming, i have issue with MyObjectBox class not rendered and this my gradle 
project.build
https://gist.github.com/anonymous/0dd00926385ca89ace30fac7d635e23d
project.build
https://gist.github.com/anonymous/2d3541cac25a4912a98524d338faffee

**Comment by PavelFpv** [comment]
You need create at least model class with @Entity annotation before go to Build > Make project

**Comment by pratikbutani** [comment]
Not @entity, Its @Entity.
