### ISSUE TITLE
Support custom serializers

### ISSUE THREAD

**Issue by BenoitDuffez** [greenrobot/ObjectBox#34]
Some non-native type fields may be serialized simply. It would be good to have them serialized automagically (or with some adaptation code of some sort) so that they can be easily accessed/changed without having to care about how they're actually stored.

The simplest example I have is a `Calendar` object, which would be serialized to a `long`.

**Comment by FabianTerhorst** [comment]
http://greenrobot.org/objectbox/documentation/custom-types

**Comment by BenoitDuffez** [comment]
Thanks. I feel dumb :)
