### ISSUE TITLE
Could not find class MyObjectBox, how to get started...

### ISSUE THREAD

**Issue by ynhenggg** [greenrobot/ObjectBox#60]
I have import ObjectBox, but I can not find class MyObjectBox, I use version 0.9.9.

I find class BoxStoreBuilder(byte[] model) ,but it needs a parameter, what does the parameter mean ?
should I use this class ?

I think I builded the project, did the api changed ?  
or how to operate to make sure the class autogeneration ?
( I already readed the "how to get start" website , but I do not get it clear )

please give some notes or tips in the code , that will be helpful ....

thanks any way ,It's a great work ,I like greenrobot always.

**Comment by ynhenggg** [comment]
finally I found it . thanks ,guys

**Comment by mandadimuralidharreddy** [comment]
@ynhenggg can you please tell how import MyObjectBox into app

**Comment by mandadimuralidharreddy** [comment]
Got it now.Need to make project  then it will create MyObjectBox.
